spring:
  servlet:
    # 文件上传相关设置
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/life_show?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&serverTimezone=GMT%2B8
    username: root
    password: xxxx
    # 连接池配置信息
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是ms
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是ms
      min-evictable-idle-time-millis: 30000
      validation-query: 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow: 127.0.0.1
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: xxxx
    initialization-mode: always
  # redis相关配置
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 1
        min-idle: 0

# 日志级别，日志文件生成位置
logging:
  level:
    root: info
    per.chao.lifeshow: info
  file:
    path: /root/lifeshow/log/

# 服务器相关配置
server:
  port: 443
  ssl:
    key-store: 'classpath:xxxx'
    key-store-type: PKCS12
    key-store-password: xxxx
    enabled: true

# mybatis plus相关配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: per.chao.lifeshow.entity
  global-config:
    db-config:
      id-type: auto

# ffmpeg工具地址
ffmpeg.tool.path: '/root/lifeshow/tool/ffmpeg'

# server url
server.url: 'https://showlife.fun'

# 文件存放位置
## bgm
bgm.path: '/root/lifeshow/bgm/audio/'
bgm.relative.path: '/bgm/play/**'
bgm.cover.path: '/root/lifeshow/bgm/cover/'
bgm.cover.relative.path: '/bgm/**'
## video
video.path: '/root/lifeshow/video/video/'
video.relative.path: '/video/play/**'
video.cover.path: '/root/lifeshow/video/cover/'
video.cover.relative.path: '/video/**'